//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {

        }

        public Task(string title, string description, DateTime dateCreated, DateTime dateBegin, DateTime dateEnd, string type,
            int prio)
        {
            Title = title;
            Description = description;
            DateCreated = dateCreated;
            DateBegin = dateBegin;
            DateEnd = dateEnd;
            Priority = prio;
            TaskType = type;
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public DateTime DateBegin { get; set; }
        public DateTime DateEnd { get; set; }
        public string TaskType { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
