//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTaskMatch
    {
        public TeamTaskMatch()
        {

        }

        public TeamTaskMatch(int tId, int tskId)
        {
            TeamID = tId;
            TaskID = tskId;
        }

        public int TeamID { get; set; }
        public int TaskID { get; set; }
    }
}
