//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using todoList.Model;

namespace todoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team : Entity
    {
        public Team()
        {

        }

        public Team(string name)
        {
            Name = name;
        }

        public override int Id { get; set; }
        public override string Name { get; set; }
    }
}
