//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeamMatch
    {
        public UserTeamMatch()
        {

        }

        public UserTeamMatch(int uID, int tID)
        {
            UserID = uID;
            TeamID = tID;
        }

        public int UserID { get; set; }
        public int TeamID { get; set; }
    }
}
