//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using todoList.Model;

namespace todoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : Entity
    {
        public User()
        {

        }

        public User(string userName, string password, string prename = null, string surname = null, string eMail = null,
            string sId = null)
        {
            Name = userName;
            Password = password;
            Prename = prename;
            Surname = surname;
            EMail = eMail;
            SkypeID = sId;
        }

        public override int Id { get; set; }
        public override string Name { get; set; }
        public string Password { get; set; }
        public string Prename { get; set; }
        public string Surname { get; set; }
        public string EMail { get; set; }
        public string SkypeID { get; set; }
    }
}
